language: node_js
node_js:
  - 13
service:
  - docker
install: 
  - echo "This is demo by minh"
before_script:
  - echo "Before script"
script:
  - docker --version
  ## build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-fontend ./udagram-fontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./reverseproxy

  ## tagging
  - docker tag udagram-api-feed nguyenxuanminh1/udagram-api-feed:v1
  - docker tag udagram-fontend nguyenxuanminh1/udagram-fontend:v1
  - docker tag uudagram-api-user nguyenxuanminh1/udagram-api-user:v1
  - docker tag reverseproxy nguyenxuanminh1/reverseproxy:v1
after_script:
  ## push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" password-stdin
  - docker push nguyenxuanminh1/udagram-api-feed:v1
  - docker push nguyenxuanminh1/udagram-fontend:v1
  - docker push nguyenxuanminh1/udagram-api-user:v1
  - docker push nguyenxuanminh1/reverseproxy:v1
  - echo "Success build docker hub"